name: Release

on:
  push:
    tags: ['v*-custom']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Archive
      run: |
        autoreconf -fvi
        make -f Makefile.aut release GIT=echo

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
