name: Release

on:
  push:
    tags:
      - v*-custom
      - v*-custom-r*

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Archive
        run: |
          autoreconf -fvi
          make -f Makefile.aut release GIT=echo

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/*/*.tar.xz
          allowUpdates: true
